name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - run: |
          git clone https://github.com/wafflecoffee/fabric
          cd fabric
          git checkout fabric-api-qsl/22w11a-fixed-screens
          ./gradlew publishToMavenLocal
        env:
          SNAPSHOT_URL: dummy
      - run: ./gradlew build
