name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle
      - env:
          SNAPSHOT_URL: dummy
        run: |
          git clone https://github.com/wafflecoffee/fabric
          cd fabric
          git checkout fabric-api-qsl/22w11a-fixed-screens
          ./gradlew publishToMavenLocal
          ls -shal --recursive .m2/repository/org/quiltmc/fabric_api_qsl/
      - run: ./gradlew build
